# Generated by Django 5.2.13 on 2026-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(help_text="e.g., 'model_comparison', 'feature_importance', 'shap_summary', 'bias_report', 'clusters'", max_length=50, unique=True)),
                ('data', models.JSONField(help_text='Stores the structured JSON output from the offline Jupyter notebook')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
